# Generated by Django 4.2.5 on 2023-11-15 19:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=55, verbose_name='Вид Комплектации')),
            ],
            options={
                'verbose_name': 'Вид Комплектации',
                'verbose_name_plural': 'Виды Комплектации',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название дома')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='Номер проекта')),
                ('main_image', models.ImageField(max_length=50, upload_to='photos/', verbose_name='Заглавное Фото')),
                ('floors', models.PositiveIntegerField(verbose_name='Количество Этажей')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество Комнат')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Количество Санузлов')),
                ('area', models.FloatField(verbose_name='Площадь м2')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RUB', 'RUB')], max_length=20, verbose_name='Валюта')),
                ('full_description', models.TextField(max_length=255, verbose_name='Полное описание')),
                ('slug', models.SlugField(unique=True)),
                ('video_url', models.TextField(blank=True, null=True, verbose_name='Cсылка на видео')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Время модификации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='SortHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид Дома',
                'verbose_name_plural': 'Виды Домов',
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название Стиля')),
            ],
            options={
                'verbose_name': 'Cтиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='schema_photos/', verbose_name='Изображение')),
                ('floor', models.PositiveIntegerField(verbose_name='Номер Этажа')),
                ('floor_point', models.TextField(verbose_name='Пункты Этажа')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировка',
            },
        ),
        migrations.CreateModel(
            name='Overhead_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('plan_title', models.CharField(max_length=100, verbose_name='Заголовок Планировки')),
                ('plan_title_description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('overhead_image', models.ImageField(upload_to='overhead_photos/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото Вида Сверху',
                'verbose_name_plural': 'Фото Вида Сверху',
            },
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interior_photos/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото Интерьера',
                'verbose_name_plural': 'Фото Интерьера',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото ',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='HousePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255, verbose_name='Пункт')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Пункт Описания Работ',
                'verbose_name_plural': 'Пункт Описания Работ',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='house_style',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housestroy.styles', verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='house',
            name='sort_of_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.sorthouse', verbose_name='Вид Дома'),
        ),
        migrations.CreateModel(
            name='Equipment_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255, verbose_name='Пункт Работ')),
                ('point_description', models.TextField(verbose_name='Описание Пункта')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RUB', 'RUB')], max_length=20, verbose_name='Валюта')),
                ('point_price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
                ('variant_of_equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.equipment_types', verbose_name='Вид Комплектации')),
            ],
            options={
                'verbose_name': 'Вариант Комплектации',
                'verbose_name_plural': 'Варианты Комплектации',
            },
        ),
        migrations.CreateModel(
            name='Equipment_Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=20, verbose_name='Название Кнопки')),
                ('button_url', models.TextField(verbose_name='Ссылка Кнопки')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='Construction_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction_photos/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото Строительства Дома',
                'verbose_name_plural': 'Фото Строительства Дома',
            },
        ),
        migrations.CreateModel(
            name='Construction_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Введите заголовок', max_length=100, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Описание Процесса Строительства',
                'verbose_name_plural': 'Описание Процесса Строительства',
            },
        ),
    ]
