# Generated by Django 4.2.5 on 2023-11-15 19:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('pers_image', models.ImageField(upload_to='personal_photos/', verbose_name='Фото')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
