# Generated by Django 4.2.5 on 2023-11-15 19:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housestroy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название Статьи')),
                ('time_reading', models.PositiveIntegerField(verbose_name='Время Прочтения Статьи (мин)')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Краткое Описание')),
                ('slug', models.SlugField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Время модификации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housestroy.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Blog_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория Статьи',
                'verbose_name_plural': 'Категории Статей',
            },
        ),
        migrations.CreateModel(
            name='Video_Blog_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('time_watching', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Краткое Описание')),
                ('main_video_url', models.TextField(verbose_name='Ссылка на Главное Видео')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Содержание Статьи')),
                ('content_video_url', models.TextField(verbose_name='Ссылка на Видео')),
                ('slug', models.SlugField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Время модификации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Видео-Блог',
                'verbose_name_plural': 'Видео-Блог',
            },
        ),
        migrations.CreateModel(
            name='BlogVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField(verbose_name='Ссылка на Видео')),
                ('blog_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='BlogStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100, verbose_name='Этап')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('blog_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='blog_photos/', verbose_name='')),
                ('blog_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Cтатья')),
                ('number_of_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogstages', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Фото Этапа',
                'verbose_name_plural': 'Фото Этапов',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='variant_of_blog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_type', verbose_name='Категория'),
        ),
    ]
