# Generated by Django 4.2.5 on 2023-11-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_variant_of_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_type',
            name='blog_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
