# Generated by Django 4.2.5 on 2023-11-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_messanger', models.CharField(max_length=100, verbose_name='Название Социальной Сети')),
                ('link_messanger', models.TextField(verbose_name='Ссылка')),
                ('messanger_image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Социальная Cеть',
                'verbose_name_plural': 'Социальные Cети',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.countrycontacts', verbose_name='Местонахождение Офиса')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_address', models.CharField(max_length=255, verbose_name='Название Офиса')),
                ('office_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.countrycontacts', verbose_name='Местонахождение Офиса')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
